### ISSUE TITLE
Allow change in sorting algorithm

### ISSUE THREAD

**Issue by pleasantone** [hbstack/gallery#82]
Right now, images in albums are sorted by name in descending order, which usually means oldest picture first.
Allow names to be sorted in ascending order as well.

**Comment by pleasantone** [comment]
Also would be nice to be able to allow it to sort by exif date instead of name, as an option.

**Comment by pleasantone** [comment]
I was thinking some more about this, and it might be possible to allow users to create their own sorting and filtering functions by inserting a hook for the image sorting code?  For example, my algorithm for sorting is now even more complex than just working off the exif date...

```
      // sort undated files by name, and then append dated files ascending
      {{- $imgs := sort (.Resources.ByType "image") "Name" "asc" }}
      {{- $dated  := slice }}
      {{- $undated := slice }}
      {{- range $imgs }}
          {{- if (and .Exif .Exif.Date) }}
              {{- $dated = $dated | append . }}
          {{- else }}
              {{- $undated = $undated | append . }}
          {{- end }}
      {{- end }}
      {{- $imgs = $undated | append (sort $dated "Exif.Date" "asc") }}
```

Please pardon the ugly template code, I'm not a golang developer.

**Comment by razonyang** [comment]
Yep, the sorting should be improved, but not all images have EXIF information, so we probably need secondary, fallback sorting  algorithms to handle those images without EXIF.

**Comment by razonyang** [comment]
Fixed since `github.com/hbstack/gallery@v0.9.0`, you're able to sort images by date in desc or asc order, and specify date for images those without EXIF information.

Read more on https://hbstack.dev/modules/gallery/overview/#images-sorting.

If you want to customize the sorting, please create the [layouts/partials/hb/modules/gallery/functions/sort-imgs.html](https://github.com/hbstack/gallery/blob/main/layouts/partials/hb/modules/gallery/functions/sort-imgs.html) on your site root.
That partial accepts an array of images that has `Image` (represents the image resources) and `Date` (the date from EXIF or params, maybe `nil`) members.

**Comment by pleasantone** [comment]
This is brilliant, thank you!
